#!/usr/bin/env bash
# Start the WebUI dev frontend and headless backend together.

set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
NC='\033[0m'

info()  { printf '%b\n' "${GREEN}[info]${NC}  $*"; }
warn()  { printf '%b\n' "${YELLOW}[warn]${NC}  $*"; }
error() { printf '%b\n' "${RED}[error]${NC} $*" >&2; }

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
STATE_DIR="${CRAFT_WEBUI_STATE_DIR:-$HOME/.craft-agent}"
ENV_FILE="${CRAFT_WEBUI_ENV_FILE:-$STATE_DIR/webui.env}"
ALLOW_INSECURE_BIND="${CRAFT_WEBUI_ALLOW_INSECURE_BIND:-true}"
KILL_PORTS="${CRAFT_WEBUI_KILL_PORTS:-true}"
SKIP_SUBPROCESS_BUILD="${CRAFT_WEBUI_SKIP_SUBPROCESS_BUILD:-false}"
BACKEND_TIMEOUT="${CRAFT_WEBUI_BACKEND_TIMEOUT:-30}"
PREFILL_TOKEN="${CRAFT_WEBUI_PREFILL_TOKEN:-true}"
ADJUST_INOTIFY="${CRAFT_WEBUI_ADJUST_INOTIFY:-true}"
MIN_INOTIFY_WATCHES="${CRAFT_WEBUI_MIN_INOTIFY_WATCHES:-524288}"
MIN_INOTIFY_INSTANCES="${CRAFT_WEBUI_MIN_INOTIFY_INSTANCES:-1024}"
MIN_INOTIFY_QUEUED_EVENTS="${CRAFT_WEBUI_MIN_INOTIFY_QUEUED_EVENTS:-32768}"

server_pid=""
webui_pid=""

ensure_bun() {
  if command -v bun >/dev/null 2>&1; then
    command -v bun
    return 0
  fi

  if [ -x "$HOME/.bun/bin/bun" ]; then
    export BUN_INSTALL="${BUN_INSTALL:-$HOME/.bun}"
    export PATH="$BUN_INSTALL/bin:$PATH"
    command -v bun
    return 0
  fi

  error "Bun is not available in PATH, and $HOME/.bun/bin/bun does not exist."
  echo "Install Bun first: curl -fsSL https://bun.sh/install | bash" >&2
  exit 1
}

generate_token() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 32
    return 0
  fi

  "$BUN_BIN" run "$REPO_ROOT/packages/server/src/index.ts" --generate-token
}

write_env_file() {
  mkdir -p "$STATE_DIR"

  cat > "$ENV_FILE" <<EOF
# Auto-generated by scripts/dev-webui.sh
CRAFT_SERVER_TOKEN=$CRAFT_SERVER_TOKEN
EOF

  chmod 600 "$ENV_FILE"
}

load_env_file() {
  if [ -f "$ENV_FILE" ]; then
    # shellcheck disable=SC1090
    . "$ENV_FILE"
  fi
}

install_deps_if_needed() {
  if [ ! -d "$REPO_ROOT/node_modules" ]; then
    info "Installing dependencies..."
    "$BUN_BIN" install --frozen-lockfile 2>/dev/null || "$BUN_BIN" install
  fi
}

is_enabled() {
  case "$(printf '%s' "$1" | tr '[:upper:]' '[:lower:]')" in
    1|true|yes|on) return 0 ;;
    *) return 1 ;;
  esac
}

is_positive_integer() {
  case "$1" in
    ''|*[!0-9]*) return 1 ;;
    *) [ "$1" -gt 0 ] ;;
  esac
}

ensure_sysctl_min() {
  local key="$1"
  local minimum="$2"
  local proc_path="/proc/sys/${key//./\/}"

  if ! is_positive_integer "$minimum"; then
    warn "Ignoring invalid $key minimum: $minimum"
    return 0
  fi

  if [ ! -r "$proc_path" ]; then
    return 0
  fi

  local current
  current="$(tr -d '[:space:]' < "$proc_path")"
  if ! is_positive_integer "$current" || [ "$current" -ge "$minimum" ]; then
    return 0
  fi

  if [ "$(id -u)" -ne 0 ]; then
    warn "$key is $current, below the recommended $minimum for Vite file watching."
    warn "Run as root or raise it manually: sudo sysctl -w $key=$minimum"
    return 0
  fi

  if sysctl -w "$key=$minimum" >/dev/null 2>&1; then
    info "Raised $key from $current to $minimum for WebUI file watching."
  else
    warn "Failed to raise $key from $current to $minimum."
  fi
}

ensure_inotify_capacity() {
  if ! is_enabled "$ADJUST_INOTIFY"; then
    return 0
  fi

  case "$(uname -s 2>/dev/null || true)" in
    Linux) ;;
    *) return 0 ;;
  esac

  ensure_sysctl_min fs.inotify.max_user_watches "$MIN_INOTIFY_WATCHES"
  ensure_sysctl_min fs.inotify.max_user_instances "$MIN_INOTIFY_INSTANCES"
  ensure_sysctl_min fs.inotify.max_queued_events "$MIN_INOTIFY_QUEUED_EVENTS"
}

kill_port() {
  local port="$1"
  local label="$2"

  if ! is_enabled "$KILL_PORTS"; then
    return 0
  fi

  if ! command -v lsof >/dev/null 2>&1; then
    warn "lsof is not available; skipping automatic cleanup for $label port $port."
    return 0
  fi

  local pids
  pids="$(lsof -tiTCP:"$port" -sTCP:LISTEN 2>/dev/null || true)"
  if [ -z "$pids" ]; then
    return 0
  fi

  warn "Stopping existing process(es) on $label port $port: $(printf '%s' "$pids" | tr '\n' ' ')"
  kill $pids 2>/dev/null || true
  sleep 1

  pids="$(lsof -tiTCP:"$port" -sTCP:LISTEN 2>/dev/null || true)"
  if [ -n "$pids" ]; then
    warn "Force-stopping process(es) on $label port $port: $(printf '%s' "$pids" | tr '\n' ' ')"
    kill -9 $pids 2>/dev/null || true
  fi
}

primary_host() {
  if [ -n "${CRAFT_WEBUI_PUBLIC_HOST:-}" ]; then
    printf '%s\n' "$CRAFT_WEBUI_PUBLIC_HOST"
    return 0
  fi

  case "$CRAFT_RPC_HOST" in
    127.0.0.1|localhost|::1)
      printf '%s\n' "$CRAFT_RPC_HOST"
      return 0
      ;;
  esac

  if command -v hostname >/dev/null 2>&1; then
    local detected
    detected="$(hostname -I 2>/dev/null | awk '{print $1}')"
    if [ -n "$detected" ]; then
      printf '%s\n' "$detected"
      return 0
    fi
  fi

  printf '127.0.0.1\n'
}

url_host() {
  case "$1" in
    *:*)
      case "$1" in
        \[*\]) printf '%s\n' "$1" ;;
        *) printf '[%s]\n' "$1" ;;
      esac
      ;;
    *) printf '%s\n' "$1" ;;
  esac
}

backend_probe_host() {
  case "$CRAFT_RPC_HOST" in
    0.0.0.0) printf '127.0.0.1\n' ;;
    ::) printf '[::1]\n' ;;
    *) url_host "$CRAFT_RPC_HOST" ;;
  esac
}

should_allow_insecure_bind() {
  if [ -n "${CRAFT_RPC_TLS_CERT:-}" ] && [ -n "${CRAFT_RPC_TLS_KEY:-}" ]; then
    return 1
  fi

  case "$CRAFT_RPC_HOST" in
    127.0.0.1|localhost|::1)
      return 1
      ;;
  esac

  is_enabled "$ALLOW_INSECURE_BIND"
}

wait_for_backend() {
  local scheme="$1"
  local host
  host="$(backend_probe_host)"
  local url="$scheme://$host:$CRAFT_RPC_PORT/health"

  if ! command -v curl >/dev/null 2>&1; then
    sleep 2
    return 0
  fi

  info "Waiting for backend health check at $url ..."
  local elapsed=0
  while [ "$elapsed" -lt "$BACKEND_TIMEOUT" ]; do
    if curl -kfsS "$url" >/dev/null 2>&1; then
      return 0
    fi

    if ! kill -0 "$server_pid" 2>/dev/null; then
      error "Backend exited before it became ready."
      return 1
    fi

    sleep 1
    elapsed=$((elapsed + 1))
  done

  error "Backend did not become ready within ${BACKEND_TIMEOUT}s."
  return 1
}

stop_pid() {
  local pid="$1"
  local label="$2"

  if [ -n "$pid" ] && kill -0 "$pid" 2>/dev/null; then
    info "Stopping $label (pid $pid)..."
    kill "$pid" 2>/dev/null || true
    wait "$pid" 2>/dev/null || true
  fi
}

cleanup() {
  local code=$?
  trap - EXIT INT TERM
  stop_pid "$webui_pid" "WebUI dev server"
  stop_pid "$server_pid" "backend server"
  exit "$code"
}

print_access_hint() {
  local backend_http_scheme="$1"
  local backend_ws_scheme="$2"
  local frontend_http_scheme="$3"
  local public_host
  public_host="$(primary_host)"
  local public_url_host
  public_url_host="$(url_host "$public_host")"
  local login_password="${CRAFT_WEBUI_PASSWORD:-$CRAFT_SERVER_TOKEN}"
  local frontend_url="$frontend_http_scheme://$public_url_host:$CRAFT_WEBUI_PORT/"

  echo ""
  info "WebUI dev stack is starting"
  echo "  repo:             $REPO_ROOT"
  echo "  env file:         $ENV_FILE"
  echo "  backend:          $backend_ws_scheme://$(url_host "$CRAFT_RPC_HOST"):$CRAFT_RPC_PORT"
  echo "  frontend:         $frontend_url"
  echo "  browser ws url:   $CRAFT_WEBUI_WS_URL"
  echo "  login password:   $login_password"
  echo ""
  echo "Open the frontend URL above; dev login will use the token automatically."
  echo "Press Ctrl+C to stop both frontend and backend."
  echo ""
}

if [ ! -f "$REPO_ROOT/package.json" ] || [ ! -d "$REPO_ROOT/apps/webui" ] || [ ! -f "$REPO_ROOT/packages/server/src/index.ts" ]; then
  error "Run this script from the craft-agents-oss repository."
  exit 1
fi

EXISTING_CRAFT_SERVER_TOKEN="${CRAFT_SERVER_TOKEN:-}"
BUN_BIN="$(ensure_bun)"
load_env_file

if [ -n "$EXISTING_CRAFT_SERVER_TOKEN" ]; then
  CRAFT_SERVER_TOKEN="$EXISTING_CRAFT_SERVER_TOKEN"
fi

export CRAFT_RPC_HOST="${CRAFT_RPC_HOST:-127.0.0.1}"
export CRAFT_RPC_PORT="${CRAFT_RPC_PORT:-9100}"
export CRAFT_WEBUI_HOST="${CRAFT_WEBUI_HOST:-0.0.0.0}"
export CRAFT_WEBUI_PORT="${CRAFT_WEBUI_PORT:-5175}"
export CRAFT_DEBUG="${CRAFT_DEBUG:-false}"
export CRAFT_BUNDLED_ASSETS_ROOT="${CRAFT_BUNDLED_ASSETS_ROOT:-$REPO_ROOT/apps/electron}"
export CRAFT_WEBUI_DIR="${CRAFT_WEBUI_DIR:-$REPO_ROOT/apps/webui/src}"

if [ -z "${CRAFT_SERVER_TOKEN:-}" ]; then
  CRAFT_SERVER_TOKEN="$(generate_token)"
  write_env_file
  info "Generated and saved a persistent CRAFT_SERVER_TOKEN to $ENV_FILE"
fi

export CRAFT_SERVER_TOKEN

if is_enabled "$PREFILL_TOKEN"; then
  export VITE_CRAFT_WEBUI_DEV_TOKEN="${CRAFT_WEBUI_PASSWORD:-$CRAFT_SERVER_TOKEN}"
else
  unset VITE_CRAFT_WEBUI_DEV_TOKEN
fi

backend_http_scheme="http"
backend_ws_scheme="ws"
if [ -n "${CRAFT_RPC_TLS_CERT:-}" ] && [ -n "${CRAFT_RPC_TLS_KEY:-}" ]; then
  backend_http_scheme="https"
  backend_ws_scheme="wss"
fi

frontend_http_scheme="$(printf '%s' "${CRAFT_WEBUI_PUBLIC_SCHEME:-http}" | tr '[:upper:]' '[:lower:]')"
frontend_ws_scheme="ws"
if [ "$frontend_http_scheme" = "https" ]; then
  frontend_ws_scheme="wss"
fi

if [ -z "${CRAFT_WEBUI_WS_URL:-}" ]; then
  detected_public_host="$(primary_host)"
  export CRAFT_WEBUI_WS_URL="$frontend_ws_scheme://$(url_host "$detected_public_host"):$CRAFT_WEBUI_PORT/ws"
fi

install_deps_if_needed
ensure_inotify_capacity

if ! is_enabled "$SKIP_SUBPROCESS_BUILD"; then
  info "Building subprocess servers..."
  (cd "$REPO_ROOT" && "$BUN_BIN" run server:build:subprocess)
fi

kill_port "$CRAFT_RPC_PORT" "backend"
kill_port "$CRAFT_WEBUI_PORT" "WebUI"

print_access_hint "$backend_http_scheme" "$backend_ws_scheme" "$frontend_http_scheme"

trap cleanup EXIT INT TERM

server_args=()
if should_allow_insecure_bind; then
  warn "Starting backend without TLS on a network address because CRAFT_WEBUI_ALLOW_INSECURE_BIND=$ALLOW_INSECURE_BIND"
  warn "Traffic and tokens are not encrypted. Use TLS for production."
  server_args+=(--allow-insecure-bind)
fi

info "Starting backend server..."
(
  cd "$REPO_ROOT"
  exec "$BUN_BIN" run packages/server/src/index.ts "${server_args[@]}"
) &
server_pid=$!

wait_for_backend "$backend_http_scheme"

info "Starting WebUI dev server..."
(
  cd "$REPO_ROOT"
  exec "$BUN_BIN" run vite dev --config apps/webui/vite.config.ts --host "$CRAFT_WEBUI_HOST" --port "$CRAFT_WEBUI_PORT" --strictPort
) &
webui_pid=$!

set +e
wait -n "$server_pid" "$webui_pid"
exit_code=$?
set -e

if [ "$exit_code" -ne 0 ]; then
  error "One process exited with status $exit_code; stopping the dev stack."
else
  warn "One process exited; stopping the dev stack."
fi
exit "$exit_code"
