#!/usr/bin/env sh

set -eu

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
NC='\033[0m'

info()  { printf '%b\n' "${GREEN}[info]${NC}  $*"; }
warn()  { printf '%b\n' "${YELLOW}[warn]${NC}  $*"; }
error() { printf '%b\n' "${RED}[error]${NC} $*" >&2; }

SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
STATE_DIR="${CRAFT_WEBUI_STATE_DIR:-$HOME/.craft-agent}"
ENV_FILE="${CRAFT_WEBUI_ENV_FILE:-$STATE_DIR/webui.env}"
HEAP_MB="${CRAFT_WEBUI_BUILD_HEAP_MB:-4096}"
ALLOW_INSECURE_BIND="${CRAFT_WEBUI_ALLOW_INSECURE_BIND:-true}"

ensure_bun() {
  if command -v bun >/dev/null 2>&1; then
    command -v bun
    return 0
  fi

  if [ -x "$HOME/.bun/bin/bun" ]; then
    export BUN_INSTALL="${BUN_INSTALL:-$HOME/.bun}"
    export PATH="$BUN_INSTALL/bin:$PATH"
    command -v bun
    return 0
  fi

  error "Bun is not available in PATH, and $HOME/.bun/bin/bun does not exist."
  echo "Install Bun first: curl -fsSL https://bun.sh/install | bash" >&2
  exit 1
}

generate_token() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 32
    return 0
  fi

  "$BUN_BIN" run "$REPO_ROOT/packages/server/src/index.ts" --generate-token
}

write_env_file() {
  mkdir -p "$STATE_DIR"

  cat > "$ENV_FILE" <<EOF
# Auto-generated by scripts/start-webui.sh
CRAFT_SERVER_TOKEN=$CRAFT_SERVER_TOKEN
EOF

  chmod 600 "$ENV_FILE"
}

load_env_file() {
  if [ -f "$ENV_FILE" ]; then
    # shellcheck disable=SC1090
    . "$ENV_FILE"
  fi
}

install_deps_if_needed() {
  if [ ! -d "$REPO_ROOT/node_modules" ]; then
    info "Installing dependencies..."
    "$BUN_BIN" install --frozen-lockfile 2>/dev/null || "$BUN_BIN" install
  fi
}

print_access_hint() {
  primary_ip=""
  protocol="http"

  if command -v hostname >/dev/null 2>&1; then
    primary_ip="$(hostname -I 2>/dev/null | awk '{print $1}')"
  fi

  if [ -n "${CRAFT_RPC_TLS_CERT:-}" ] && [ -n "${CRAFT_RPC_TLS_KEY:-}" ]; then
    protocol="https"
  fi

  echo ""
  info "WebUI startup configuration"
  echo "  repo:        $REPO_ROOT"
  echo "  bun:         $BUN_BIN"
  echo "  env file:    $ENV_FILE"
  echo "  host:        $CRAFT_RPC_HOST"
  echo "  port:        $CRAFT_RPC_PORT"
  echo "  heap:        ${HEAP_MB} MB"
  echo "  tls:         $protocol"
  echo "  token:       $CRAFT_SERVER_TOKEN"

  if [ -n "$primary_ip" ]; then
    echo "  access:      $protocol://$primary_ip:$CRAFT_RPC_PORT"
  elif [ "$CRAFT_RPC_HOST" != "0.0.0.0" ]; then
    echo "  access:      $protocol://$CRAFT_RPC_HOST:$CRAFT_RPC_PORT"
  else
    echo "  access:      $protocol://<server-ip>:$CRAFT_RPC_PORT"
  fi

  echo ""
}

should_allow_insecure_bind() {
  if [ -n "${CRAFT_RPC_TLS_CERT:-}" ] && [ -n "${CRAFT_RPC_TLS_KEY:-}" ]; then
    return 1
  fi

  case "$CRAFT_RPC_HOST" in
    127.0.0.1|localhost|::1)
      return 1
      ;;
  esac

  case "$(printf '%s' "$ALLOW_INSECURE_BIND" | tr '[:upper:]' '[:lower:]')" in
    1|true|yes|on)
      return 0
      ;;
    *)
      return 1
      ;;
  esac
}

if [ ! -f "$REPO_ROOT/package.json" ] || [ ! -d "$REPO_ROOT/apps/webui" ]; then
  error "Run this script from the craft-agents-oss repository."
  exit 1
fi

EXISTING_CRAFT_SERVER_TOKEN="${CRAFT_SERVER_TOKEN:-}"
BUN_BIN="$(ensure_bun)"
load_env_file

if [ -n "$EXISTING_CRAFT_SERVER_TOKEN" ]; then
  CRAFT_SERVER_TOKEN="$EXISTING_CRAFT_SERVER_TOKEN"
fi

export CRAFT_RPC_HOST="${CRAFT_RPC_HOST:-0.0.0.0}"
export CRAFT_RPC_PORT="${CRAFT_RPC_PORT:-9100}"
export CRAFT_DEBUG="${CRAFT_DEBUG:-true}"
export CRAFT_BUNDLED_ASSETS_ROOT="$REPO_ROOT/apps/electron"
export CRAFT_WEBUI_DIR="$REPO_ROOT/apps/webui/dist"

if [ -z "${CRAFT_SERVER_TOKEN:-}" ]; then
  CRAFT_SERVER_TOKEN="$(generate_token)"
  write_env_file
  info "Generated and saved a persistent CRAFT_SERVER_TOKEN to $ENV_FILE"
fi

export CRAFT_SERVER_TOKEN

install_deps_if_needed
print_access_hint

info "Building subprocess servers..."
"$BUN_BIN" run server:build:subprocess

info "Building WebUI with increased Node heap..."
NODE_OPTIONS="--max-old-space-size=$HEAP_MB ${NODE_OPTIONS:-}" "$BUN_BIN" run webui:build

info "Starting server with embedded WebUI..."
if should_allow_insecure_bind; then
  warn "Starting without TLS on a network address because CRAFT_WEBUI_ALLOW_INSECURE_BIND=$ALLOW_INSECURE_BIND"
  warn "Traffic and token are not encrypted. Use TLS for production."
  exec "$BUN_BIN" run packages/server/src/index.ts --allow-insecure-bind
fi

exec "$BUN_BIN" run packages/server/src/index.ts
